import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';

import '../models/appointment.dart';
import '../models/article.dart';
import '../models/doctor.dart';
import '../models/family_member.dart';
import '../models/notification.dart';
import '../models/records.dart';
import '../models/review.dart';
import '../models/slot.dart';
import '../models/specialty.dart';
import '../models/user.dart';

part 'curae_api.g.dart';

/// Typed REST client over the mock json-server API. Generated by retrofit.
@RestApi()
abstract class CuraeApi {
  factory CuraeApi(Dio dio, {String? baseUrl}) = _CuraeApi;

  // --- auth ---
  @POST('/auth/login')
  Future<AuthResponse> login(@Body() Map<String, dynamic> body);

  @POST('/auth/register')
  Future<AuthResponse> register(@Body() Map<String, dynamic> body);

  @GET('/auth/me')
  Future<MeResponse> me();

  // --- catalogue ---
  @GET('/specialties')
  Future<List<Specialty>> specialties();

  @GET('/doctors')
  Future<HttpResponse<List<Doctor>>> doctors({
    @Queries() Map<String, dynamic>? queries,
  });

  @GET('/doctors/{id}')
  Future<Doctor> doctor(@Path('id') String id);

  @GET('/doctors/{id}/reviews')
  Future<List<Review>> reviews(@Path('id') String id);

  @GET('/doctors/{id}/slots')
  Future<List<DaySlots>> slots(
    @Path('id') String id, {
    @Query('date') String? date,
  });

  // --- appointments ---
  @GET('/appointments')
  Future<List<Appointment>> appointments({
    @Queries() Map<String, dynamic>? queries,
  });

  @GET('/appointments/{id}')
  Future<Appointment> appointment(@Path('id') String id);

  @POST('/appointments')
  Future<Appointment> createAppointment(@Body() Map<String, dynamic> body);

  @PATCH('/appointments/{id}')
  Future<Appointment> patchAppointment(
    @Path('id') String id,
    @Body() Map<String, dynamic> body,
  );

  // --- records / family / content ---
  @GET('/records')
  Future<HealthRecords> records();

  @GET('/family-members')
  Future<List<FamilyMember>> familyMembers();

  @POST('/family-members')
  Future<FamilyMember> createFamilyMember(@Body() Map<String, dynamic> body);

  @PATCH('/family-members/{id}')
  Future<FamilyMember> patchFamilyMember(
    @Path('id') String id,
    @Body() Map<String, dynamic> body,
  );

  @DELETE('/family-members/{id}')
  Future<void> deleteFamilyMember(@Path('id') String id);

  @GET('/articles')
  Future<List<Article>> articles();

  @GET('/articles/{id}')
  Future<Article> article(@Path('id') String id);

  @GET('/notifications')
  Future<List<AppNotification>> notifications();

  @PATCH('/notifications/{id}')
  Future<AppNotification> patchNotification(
    @Path('id') String id,
    @Body() Map<String, dynamic> body,
  );
}
